### ISSUE TITLE
Strapi authentication error: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by edvard-rgb** [strapi/gatsby-source-strapi#250]
Hi,

I'm getting the following error when I try to use the gatsby-source-strapi plugin in production. 

```
success load plugins - 0.776s
success onPreInit - 0.065s
success initialize cache - 0.005s
success copy gatsby files - 0.039s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.006s

 ERROR

Strapi authentication error: Error: connect ETIMEDOUT XXX.XXX.XXX.XXX:443

not finished source and transform nodes - 130.671s
not finished Authenticate Strapi User - 130.323s
```

I use docker together with Traefik.

docker-compose

```
version: "2.4"
services:
  web:
    build: "."
    ports:
      - "8000:80"
    volumes:
      - "./data:/data:rw"
    env_file: .env
    labels:
      traefik.enable: true
      traefik.http.routers.web-gatsby.entrypoints: https
      traefik.http.routers.web-gatsby.rule: Host("x.x.com")
      traefik.http.routers.web-gatsby.service: web-gatsby
      traefik.http.services.web-gatsby.loadbalancer.server.port: 80
      traefik.docker.network: web
    networks:
      - web

networks:
  web:
    external: true

`````

Dockerfile:

```
FROM node:14.15.1-alpine

EXPOSE 80

RUN apk add --no-cache \
  git \
  util-linux openssl sudo \
  python g++ \
  autoconf automake libtool gcc make musl-dev file pkgconfig nasm && \
  apk add vips-dev fftw-dev --update-cache \
  && rm -fR /var/cache/apk/*

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn --update-checksums

COPY . /app

RUN yarn start
```

package.json

```
{
  "name": "website",
  "private": true,
  "description": "website",
  "version": "0.1.0",
  "author": "webmaster",
  "dependencies": {
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.1.4",
    "@emotion/styled": "^11.0.0",
    "axios": "^0.21.1",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "gatsby": "^2.31.1",
    "gatsby-image": "^2.10.0",
    "gatsby-plugin-emotion": "^5.3.0",
    "gatsby-plugin-feed": "^2.12.0",
    "gatsby-plugin-fixhash": "^0.0.4",
    "gatsby-plugin-google-marketing-platform": "^0.1.21",
    "gatsby-plugin-google-tagmanager": "^2.10.0",
    "gatsby-plugin-gtag": "^1.0.13",
    "gatsby-plugin-manifest": "^2.11.0",
    "gatsby-plugin-netlify": "^2.10.0",
    "gatsby-plugin-react-helmet": "^3.9.0",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-robots-txt": "^1.5.5",
    "gatsby-plugin-sharp": "^2.13.1",
    "gatsby-plugin-sitemap": "^2.11.0",
    "gatsby-plugin-webpack-bundle-analyser-v2": "^1.1.21",
    "gatsby-source-drupal": "^3.12.0",
    "gatsby-source-filesystem": "^2.10.0",
    "gatsby-transformer-json": "^2.10.0",
    "gatsby-transformer-sharp": "^2.11.0",
    "netlify-lambda": "^2.0.3",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-player": "^2.8.1",
    "react-slick": "^0.28.0",
    "react-spring": "^8.0.27",
    "slick-carousel": "^1.8.1"
  },
  "devDependencies": {
    "babel-eslint": "~10.1.0",
    "cypress": "^6.3.0",
    "eslint": "~7.18.0",
    "eslint-config-airbnb": "~18.2.1",
    "eslint-config-prettier": "~7.2.0",
    "eslint-plugin-cypress": "^2.11.2",
    "eslint-plugin-import": "~2.22.1",
    "eslint-plugin-jsx-a11y": "~6.4.1",
    "eslint-plugin-prettier": "~3.3.1",
    "eslint-plugin-react": "~7.22.0",
    "eslint-plugin-react-hooks": "4.2.0",
    "husky": "~4.3.8",
    "jest": "^26.6.3",
    "prettier": "~2.2.1",
    "pretty-quick": "~3.1.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "cross-env GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages --verbose",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "yarn run build",
    "serve": "gatsby serve",
    "cypress": "cypress open",
    "test": "cypress run",
    "lint": "node ./node_modules/eslint/bin/eslint . --ignore-path .gitignore",
    "lambda": "netlify-lambda build ./static/functions"
  },
  "husky": {
    "hooks": {
      "commit-msg": "npm run lint",
      "pre-commit": "pretty-quick --staged"
    }
  }
}
```

Finally, the plugin part in gatsby-config.js:

   ```
 {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: process.env.API_URL,
        queryLimit: 1000, // Default to 100
        contentTypes: ['article', 'user'],
        //If using single types place them in this array.
        singleTypes: ['home-page', 'contact'],
        // Possibility to login with a strapi user, when content types are not publically available (optional).
        loginData: {
          identifier: process.env.API_EMAIL,
          password: process.env.API_PASSWORD,
        },
      },
    },
```

Any suggestions?

Thanks in advance.
